// Re-export design tokens
// These are generated by the build process and will be available after building
export * from './tokens';

// Type definitions for design tokens
export interface DesignTokens {
  colors: Record<string, any>;
  spacing: Record<string, string>;
  typography: Record<string, any>;
  radius: Record<string, string>;
  shadow: Record<string, string>;
  zIndex: Record<string, string>;
  breakpoints: Record<string, string>;
}